default:
  image: $CI_REGISTRY_IMAGE/builder

stages:
- prep
- build

prepare builder image:
  stage: prep
  only:
    changes:
    - builder.dockerfile
    - Gemfile
    - Gemfile.lock
  image: docker:dind
  services:
    - name: docker:dind

  script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  
  - docker pull $CI_REGISTRY_IMAGE/builder:latest || echo Not built yet
  - docker build -t $CI_REGISTRY_IMAGE/builder -f builder.dockerfile --cache-from $CI_REGISTRY_IMAGE/builder:latest .
  - docker push $CI_REGISTRY_IMAGE/builder

build:
  stage: build
  script:
  - bundle install
  - rake cmake
  - rake build
